spring.application.name=cqapi
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.connections.pooling=WARN

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

sentry.dsn=https://42edcb5f19efd185a7eb9a4aecf84fa4@o4511576910200832.ingest.us.sentry.io/4511576912625665
# Add data like request headers and IP for users,
# see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
sentry.send-default-pii=true
# Enable sending logs to Sentry
sentry.logs.enabled=true
# Set traces-sample-rate to 1.0 to capture 100% of transactions for tracing.
# We recommend adjusting this value in production.
sentry.traces-sample-rate=1.0
# Set profile-session-sample-rate to 1.0 to profile 100% of profile sessions.
sentry.profile-session-sample-rate=1.0
# Set profile-lifecycle to trace to automatically start and stop
# profiling when a transaction starts and finishes.
sentry.profile-lifecycle=TRACE