spring.application.name=cqapi

# Conexão com PostgreSQL
spring.datasource.url=jdbc:postgresql://postgresql:5432/climaquest
spring.datasource.username=cqAPI
spring.datasource.password=cqapi@2026@fae

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
